# Generated by Django 4.2.14 on 2024-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed')], default=0),
        ),
    ]
