# Generated by Django 4.2.14 on 2024-08-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='content',
            new_name='carer',
        ),
    ]
