# Generated by Django 4.2.14 on 2024-08-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0005_rename_content_schedule_carer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clnt_Evnt_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
