# Generated by Django 4.2.14 on 2024-08-01 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0006_alter_schedule_client_clnt_evnt_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clnt_Evnt_Notes',
            new_name='ClientEventNote',
        ),
    ]
