# Generated by Django 4.2.14 on 2024-08-01 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0007_rename_clnt_evnt_notes_clienteventnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteventnote',
            old_name='created_on',
            new_name='note_created',
        ),
        migrations.AlterField(
            model_name='clienteventnote',
            name='cal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='clienteventnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_event_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
