# Generated by Django 4.2.14 on 2024-08-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_rename_created_on_clienteventnote_note_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start', 'client']},
        ),
    ]
