# Generated by Django 4.2.14 on 2024-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_clienteventnote_slug_clienteventnote_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteventnote',
            name='cal_id',
        ),
        migrations.RemoveField(
            model_name='clienteventnote',
            name='start',
        ),
        migrations.AddField(
            model_name='clienteventnote',
            name='event_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
